name: Generate PDF from HTML

on:
  push:
    branches:
      - main

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: auto-pdf

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate PDF
        run: npm start

      - name: Upload generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: curriculo.pdf
          path: curriculo.pdf
